parameters:
  - name: Daily
    type: boolean
    default: true
  - name: Artifacts
    type: object
    default: []
  - name: ArtifactName
    type: string
    default: ""

jobs:
  - template: ./smoke-test-job.yml
    parameters:
      Timeout: 30
      MaxParallel: 2
      Daily: ${{ parameters.Daily }}
      Artifacts: ${{ parameters.Artifacts }}
      ArtifactName: ${{ parameters.ArtifactName }}

      TestTask:
        task: Maven@3
        displayName: 'Run Smoke Test Samples'
        inputs:
          mavenPomFile: $(PomFile)
          goals: 'test'
          options: '$(DefaultOptions) -Dtest=**/*Example.java,**/*Sample.java'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaTestVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
        env:
          AZURE_LOG_LEVEL: 2

      Matrix:
        Service Bus:
          JavaTestVersion: '1.8'
          OSVmImage: windows-2019
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
          PomFile: sdk/servicebus/azure-messaging-servicebus/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/sdk/servicebus/'

  - template: ./smoke-test-job.yml
    parameters:
      TestTask:
        task: Maven@3
        displayName: 'Run Smoke Tests'
        inputs:
          mavenPomFile: $(PomFile)
          goals: 'exec:java'
          options: '$(DefaultOptions) -Dexec.mainClass="com.azure.smoketest.App"'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaTestVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
        env:
          AZURE_LOG_LEVEL: 2

      Matrix:
        Java 8 Windows (AzureCloud):
          JavaTestVersion: '1.8'
          OSVmImage: windows-2019
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
        Java LTS Windows (AzureCloud):
          JavaTestVersion: '1.11'
          OSVmImage: windows-2019
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
        Java 8 Linux (AzureCloud):
          JavaTestVersion: '1.8'
          OSVmImage: ubuntu-18.04
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
        Java LTS Linux (AzureCloud):
          JavaTestVersion: '1.11'
          OSVmImage: ubuntu-18.04
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
        Java LTS Linux (AzureCloud Canary):
          JavaTestVersion: '1.11'
          OSVmImage: ubuntu-18.04
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)
          ArmTemplateParameters: $(azureCloudArmParameters)
          Location: 'eastus2euap'
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
        Java 8 MacOS (AzureCloud):
          JavaTestVersion: '1.8'
          OSVmImage: macOS-10.15
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
        Java LTS MacOS (AzureCloud):
          JavaTestVersion: '1.11'
          OSVmImage: macOS-10.15
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
        Java 8 Windows (AzureUSGovernment):
          JavaTestVersion: '1.8'
          OSVmImage: windows-2019
          SubscriptionConfiguration: $(sub-config-gov-test-resources)
          ArmTemplateParameters: $(azureUSGovernmentArmParameters)
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
        Java LTS Windows (AzureUSGovernment):
          JavaTestVersion: '1.11'
          OSVmImage: windows-2019
          SubscriptionConfiguration: $(sub-config-gov-test-resources)
          ArmTemplateParameters: $(azureUSGovernmentArmParameters)
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
        Java 8 Windows (AzureChinaCloud):
          JavaTestVersion: '1.8'
          OSVmImage: windows-2019
          SubscriptionConfiguration: $(sub-config-cn-test-resources)
          ArmTemplateParameters: $(azureChinaCloudArmParameters)
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
        Java LTS Windows (AzureChinaCloud):
          JavaTestVersion: '1.11'
          OSVmImage: windows-2019
          SubscriptionConfiguration: $(sub-config-cn-test-resources)
          ArmTemplateParameters: $(azureChinaCloudArmParameters)
          PomFile: common/smoke-tests/pom.xml
          ServiceDirectory: '$(Build.SourcesDirectory)/common/smoke-tests/'
