trigger: none

variables:
  - template: /eng/pipelines/templates/variables/globals.yml

stages:
  - stage: smoke_tests
    displayName: Smoke Tests
    jobs:
      - template: /eng/pipelines/templates/jobs/smoke-test-dependencies.yml
  - stage: smoke_tests_samples
    displayName: Smoke Test Samples
    dependsOn: []
    jobs:
      - template: /eng/pipelines/templates/jobs/smoke-test-samples.yml
