parameters:
  Artifacts: []
  SDKType: management
  ServiceDirectory: not-specified

stages:
- stage: 'Build'

  variables:
    BuildOptions: '--batch-mode -Dgpg.skip -Dmaven.wagon.http.pool=false'
    ProfileFlag: ''

  jobs:
  - job:

    variables:
      - template: ../variables/globals.yml

    strategy:
      matrix:
        Java 8:
          ArtifactName: 'packages'
          JavaVersion: '1.8'
        Java 7:
          ArtifactName: 'packages'
          JavaVersion: '1.7'

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      # Java 7 was removed from the hosted agents via https://github.com/actions/virtual-environments/issues/2446.
      # Step copied from https://github.com/actions/virtual-environments/pull/2633/files#diff-38b50849f7a1c5a5f1b413356b0eb9517ed6aa31ba1c97afc1e0c07e62735f33
      - script: |
          apt-get -y install zulu-7-azure-jdk=\*
          echo "JAVA_HOME_7_X64=/usr/lib/jvm/zulu-7-azure-amd64" | tee -a /etc/environment
        condition: eq(variables['JavaVersion'], '1.7')

      - task: Maven@3
        displayName: 'Build'
        inputs:
          mavenPomFile: sdk/${{parameters.ServiceDirectory}}/pom.mgmt.xml
          goals: 'compile'
          options: '$(BuildOptions) $(ProfileFlag) "-DpackageOutputDirectory=$(Build.ArtifactStagingDirectory)" -DskipTests'
          mavenOptions: '$(MemoryOptions) $(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          mergeTestResults: true
          testRunTitle: 'On Java $(JavaVersion)'
